// Human-facing wording for the sampled World Values Survey questions.
//
// Each entry's `code` matches a question in src/data/wvs.json (which holds the
// numeric scale + normalized country means). The numeric `value` of every
// answer option corresponds to the original WVS response code, so a user's
// answer lives on the exact same scale as the country data it is compared to.
//
// Question types:
//   - "choice": discrete labelled options (Likert-style).
//   - "scale":  an N-point scale rendered as numbered buttons with end labels.

export const QUESTIONS = [
  {
    code: "Q1",
    type: "choice",
    category: "Family & Belonging",
    text: "How important is family in your life?",
    options: [
      { value: 1, label: "Very important" },
      { value: 2, label: "Rather important" },
      { value: 3, label: "Not very important" },
      { value: 4, label: "Not at all important" },
    ],
  },
  {
    code: "Q27",
    type: "choice",
    category: "Family & Duty",
    text: "Making my parents proud has been one of my main goals in life.",
    options: [
      { value: 1, label: "Agree strongly" },
      { value: 2, label: "Agree" },
      { value: 3, label: "Disagree" },
      { value: 4, label: "Strongly disagree" },
    ],
  },
  {
    code: "Q37",
    type: "choice",
    category: "Family & Duty",
    text: "It is a duty towards society to have children.",
    options: [
      { value: 1, label: "Agree strongly" },
      { value: 2, label: "Agree" },
      { value: 3, label: "Neither agree nor disagree" },
      { value: 4, label: "Disagree" },
      { value: 5, label: "Strongly disagree" },
    ],
  },
  {
    code: "Q38",
    type: "choice",
    category: "Family & Duty",
    text: "Adult children have the duty to provide long-term care for their parents.",
    options: [
      { value: 1, label: "Agree strongly" },
      { value: 2, label: "Agree" },
      { value: 3, label: "Neither agree nor disagree" },
      { value: 4, label: "Disagree" },
      { value: 5, label: "Strongly disagree" },
    ],
  },
  {
    code: "Q5",
    type: "choice",
    category: "Family & Duty",
    text: "How important is work in your life?",
    options: [
      { value: 1, label: "Very important" },
      { value: 2, label: "Rather important" },
      { value: 3, label: "Not very important" },
      { value: 4, label: "Not at all important" },
    ],
  },
  {
    code: "Q164",
    type: "scale",
    category: "Faith & Spirituality",
    text: "How important is God in your life?",
    lowLabel: "Not at all important",
    highLabel: "Very important",
  },
  {
    code: "Q169",
    type: "choice",
    category: "Faith & Spirituality",
    text: "Whenever science and religion conflict, religion is always right.",
    options: [
      { value: 1, label: "Strongly agree" },
      { value: 2, label: "Agree" },
      { value: 3, label: "Disagree" },
      { value: 4, label: "Strongly disagree" },
    ],
  },
  {
    code: "Q170",
    type: "choice",
    category: "Faith & Spirituality",
    text: "The only acceptable religion is my religion.",
    options: [
      { value: 1, label: "Strongly agree" },
      { value: 2, label: "Agree" },
      { value: 3, label: "Disagree" },
      { value: 4, label: "Strongly disagree" },
    ],
  },
  {
    code: "Q166",
    type: "choice",
    category: "Faith & Spirituality",
    text: "Do you believe in life after death?",
    options: [
      { value: 1, label: "Yes" },
      { value: 2, label: "No" },
    ],
  },
  {
    code: "Q168",
    type: "choice",
    category: "Faith & Spirituality",
    text: "Do you believe in heaven?",
    options: [
      { value: 1, label: "Yes" },
      { value: 2, label: "No" },
    ],
  },
  {
    code: "Q167",
    type: "choice",
    category: "Faith & Spirituality",
    text: "Do you believe in hell?",
    options: [
      { value: 1, label: "Yes" },
      { value: 2, label: "No" },
    ],
  },
  {
    code: "Q158",
    type: "scale",
    category: "Science & Society",
    text: "Science and technology are making our lives healthier, easier, and more comfortable.",
    lowLabel: "Completely disagree",
    highLabel: "Completely agree",
  },
  {
    code: "Q163",
    type: "scale",
    category: "Science & Society",
    text: "All things considered, is the world better or worse off because of science and technology?",
    lowLabel: "A lot worse off",
    highLabel: "A lot better off",
  },
  {
    code: "Q182",
    type: "scale",
    category: "Personal Freedom",
    text: "Is homosexuality justifiable?",
    lowLabel: "Never justifiable",
    highLabel: "Always justifiable",
  },
  {
    code: "Q240",
    type: "scale",
    category: "Politics",
    text: "In political matters, where would you place your views?",
    lowLabel: "The Left",
    highLabel: "The Right",
  },
  {
    code: "Q235",
    type: "choice",
    category: "Governance",
    text: "Having a strong leader who does not have to bother with parliament and elections would be...",
    options: [
      { value: 1, label: "A very good way of governing" },
      { value: 2, label: "Fairly good" },
      { value: 3, label: "Fairly bad" },
      { value: 4, label: "A very bad way of governing" },
    ],
  },
  {
    code: "Q237",
    type: "choice",
    category: "Governance",
    text: "Having the army rule the country would be...",
    options: [
      { value: 1, label: "A very good way of governing" },
      { value: 2, label: "Fairly good" },
      { value: 3, label: "Fairly bad" },
      { value: 4, label: "A very bad way of governing" },
    ],
  },
  {
    code: "Q196",
    type: "choice",
    category: "Governance",
    text: "Should the government have the right to keep people under video surveillance in public areas?",
    options: [
      { value: 1, label: "Definitely should have the right" },
      { value: 2, label: "Probably should have the right" },
      { value: 3, label: "Probably should not have the right" },
      { value: 4, label: "Definitely should not have the right" },
    ],
  },
  {
    code: "Q197",
    type: "choice",
    category: "Governance",
    text: "Should the government have the right to monitor all emails and other information exchanged on the Internet?",
    options: [
      { value: 1, label: "Definitely should have the right" },
      { value: 2, label: "Probably should have the right" },
      { value: 3, label: "Probably should not have the right" },
      { value: 4, label: "Definitely should not have the right" },
    ],
  },
  {
    code: "Q198",
    type: "choice",
    category: "Governance",
    text: "Should the government have the right to collect information about anyone living in this country without their knowledge?",
    options: [
      { value: 1, label: "Definitely should have the right" },
      { value: 2, label: "Probably should have the right" },
      { value: 3, label: "Probably should not have the right" },
      { value: 4, label: "Definitely should not have the right" },
    ],
  },
  {
    code: "Q149",
    type: "choice",
    category: "Politics",
    text: "Which is more important: freedom or equality?",
    options: [
      { value: 1, label: "Freedom" },
      { value: 2, label: "Equality" },
    ],
  },
  {
    code: "Q29",
    type: "choice",
    category: "Gender & Society",
    text: "On the whole, men make better political leaders than women do.",
    options: [
      { value: 1, label: "Agree strongly" },
      { value: 2, label: "Agree" },
      { value: 3, label: "Disagree" },
      { value: 4, label: "Strongly disagree" },
    ],
  },
  {
    code: "Q30",
    type: "choice",
    category: "Gender & Society",
    text: "A university education is more important for a boy than for a girl.",
    options: [
      { value: 1, label: "Agree strongly" },
      { value: 2, label: "Agree" },
      { value: 3, label: "Disagree" },
      { value: 4, label: "Strongly disagree" },
    ],
  },
  {
    code: "Q33",
    type: "choice",
    category: "Gender & Society",
    text: "When jobs are scarce, men should have more right to a job than women.",
    options: [
      { value: 1, label: "Agree strongly" },
      { value: 2, label: "Agree" },
      { value: 3, label: "Neither agree nor disagree" },
      { value: 4, label: "Disagree" },
      { value: 5, label: "Strongly disagree" },
    ],
  },
  {
    code: "Q35",
    type: "choice",
    category: "Gender & Society",
    text: "If a woman earns more money than her husband, it's almost certain to cause problems.",
    options: [
      { value: 1, label: "Agree strongly" },
      { value: 2, label: "Agree" },
      { value: 3, label: "Neither agree nor disagree" },
      { value: 4, label: "Disagree" },
      { value: 5, label: "Strongly disagree" },
    ],
  },
  {
    code: "Q22",
    type: "choice",
    category: "Tolerance & Neighbours",
    text: "Would it bother you to have homosexuals as neighbours?",
    options: [
      { value: 1, label: "Yes, I'd rather not" },
      { value: 2, label: "No, it wouldn't bother me" },
    ],
  },
  {
    code: "Q184",
    type: "scale",
    category: "Personal Freedom",
    text: "Is abortion justifiable?",
    lowLabel: "Never justifiable",
    highLabel: "Always justifiable",
  },
  {
    code: "Q193",
    type: "scale",
    category: "Personal Freedom",
    text: "Is having casual sex justifiable?",
    lowLabel: "Never justifiable",
    highLabel: "Always justifiable",
  },
  {
    code: "Q57",
    type: "choice",
    category: "Trust",
    text: "Generally speaking, would you say that...",
    options: [
      { value: 1, label: "Most people can be trusted" },
      { value: 2, label: "You need to be very careful" },
    ],
  },
  {
    code: "Q63",
    type: "choice",
    category: "Openness to the World",
    text: "How much do you trust people of another nationality?",
    options: [
      { value: 1, label: "Trust completely" },
      { value: 2, label: "Trust somewhat" },
      { value: 3, label: "Not very much" },
      { value: 4, label: "Not at all" },
    ],
  },
  {
    code: "Q259",
    type: "choice",
    category: "Openness to the World",
    text: "How close do you feel to the world as a whole?",
    options: [
      { value: 1, label: "Very close" },
      { value: 2, label: "Close" },
      { value: 3, label: "Not very close" },
      { value: 4, label: "Not close at all" },
    ],
  },
  {
    code: "Q21",
    type: "choice",
    category: "Tolerance & Neighbours",
    text: "Would it bother you to have immigrants or foreign workers as neighbours?",
    options: [
      { value: 1, label: "Yes, I'd rather not" },
      { value: 2, label: "No, it wouldn't bother me" },
    ],
  },
  {
    code: "Q250",
    type: "scale",
    category: "Politics",
    text: "How important is it for you to live in a country that is governed democratically?",
    lowLabel: "Not at all important",
    highLabel: "Absolutely important",
  },
  {
    code: "Q209",
    type: "choice",
    category: "Civic Action",
    text: "Signing a petition — is this something you...",
    options: [
      { value: 1, label: "Have actually done" },
      { value: 2, label: "Might do" },
      { value: 3, label: "Would never do" },
    ],
  },
  {
    code: "Q6",
    type: "choice",
    category: "Faith & Spirituality",
    text: "How important is religion in your life?",
    options: [
      { value: 1, label: "Very important" },
      { value: 2, label: "Rather important" },
      { value: 3, label: "Not very important" },
      { value: 4, label: "Not at all important" },
    ],
  },
  {
    code: "Q106",
    type: "scale",
    category: "Economy",
    text: "Where do you stand on incomes?",
    lowLabel: "Incomes should be made more equal",
    highLabel: "We need larger income differences as incentives",
  },
  {
    code: "Q108",
    type: "scale",
    category: "Economy",
    text: "Where do you stand on government versus individual responsibility?",
    lowLabel: "The government should take more responsibility to ensure that everyone is provided for",
    highLabel: "People should take more responsibility to provide for themselves",
  },
  {
    code: "Q111",
    type: "choice",
    category: "Environment",
    text: "Which should be given priority?",
    options: [
      { value: 1, label: "Protecting the environment" },
      { value: 2, label: "Economic growth and creating jobs" },
    ],
  },
  {
    code: "Q254",
    type: "choice",
    category: "Nation & Identity",
    text: "How proud are you to be of your nationality?",
    options: [
      { value: 1, label: "Very proud" },
      { value: 2, label: "Quite proud" },
      { value: 3, label: "Not very proud" },
      { value: 4, label: "Not at all proud" },
    ],
  },
  {
    code: "Q19",
    type: "choice",
    category: "Tolerance & Neighbours",
    text: "Would it bother you to have people of a different race as neighbours?",
    options: [
      { value: 1, label: "Yes, I'd rather not" },
      { value: 2, label: "No, it wouldn't bother me" },
    ],
  },
  {
    code: "Q185",
    type: "scale",
    category: "Personal Freedom",
    text: "Is divorce justifiable?",
    lowLabel: "Never justifiable",
    highLabel: "Always justifiable",
  },
  {
    code: "Q188",
    type: "scale",
    category: "Personal Freedom",
    text: "Is euthanasia justifiable?",
    lowLabel: "Never justifiable",
    highLabel: "Always justifiable",
  },
  {
    code: "Q183",
    type: "scale",
    category: "Ethics",
    text: "Is prostitution justifiable?",
    lowLabel: "Never justifiable",
    highLabel: "Always justifiable",
  },
  {
    code: "Q187",
    type: "scale",
    category: "Life & Death",
    text: "Is suicide justifiable?",
    lowLabel: "Never justifiable",
    highLabel: "Always justifiable",
  },
  {
    code: "Q195",
    type: "scale",
    category: "Life & Death",
    text: "Is the death penalty justifiable?",
    lowLabel: "Never justifiable",
    highLabel: "Always justifiable",
  },
  {
    code: "Q45",
    type: "choice",
    category: "Authority & Order",
    text: "If greater respect for authority were to happen, would it be...",
    options: [
      { value: 1, label: "A good thing" },
      { value: 2, label: "I don't mind" },
      { value: 3, label: "A bad thing" },
    ],
  },
  {
    code: "Q109",
    type: "scale",
    category: "Economy",
    text: "Where do you stand on competition?",
    lowLabel: "Competition is good; it spurs people to work hard",
    highLabel: "Competition is harmful; it brings out the worst in people",
  },
  {
    code: "Q179",
    type: "scale",
    category: "Ethics",
    text: "Is stealing property justifiable?",
    lowLabel: "Never justifiable",
    highLabel: "Always justifiable",
  },
  {
    code: "Q180",
    type: "scale",
    category: "Ethics",
    text: "Is cheating on taxes if you have a chance justifiable?",
    lowLabel: "Never justifiable",
    highLabel: "Always justifiable",
  },
  {
    code: "Q181",
    type: "scale",
    category: "Ethics",
    text: "Is someone accepting a bribe in the course of their duties justifiable?",
    lowLabel: "Never justifiable",
    highLabel: "Always justifiable",
  },
];
